### ISSUE TITLE
Getting issue while mapDispatchToProps

### ISSUE THREAD

**Issue by vivekshah-zymr** [ItsNoHax/EventFinder#1]
Hello, I am implementing react-native-navigation V2 with redux as you mentioned over the master branch. But when I use `mapDispatchToProps` it gives me an error like "undefined is not an object (evaluating 'this.props.onRegister')"
Below is the snippet from my code. Please help me out.
Screen1 code
```
didTapSave() {
        let newTrucker = {
            fullName: 'Test Name From 1st screen',
            phoneNumber: '97645',
        };
        this.props.onRegister(newUser);
    }

const mapDispatchToProps = dispatch => ({
    onRegister: (request) => dispatch(registerUser(request))
});
export default connect(mapStateToProps, mapDispatchToProps)(File1Screen);
```

**Comment by ItsNoHax** [comment]
@vivekshah-zymr Your method didTapSave is not binded. What that means is it has no access to 'this'.
Try the following:
```
didTapSave = () => {
    let newTrucker = {
        fullName: 'Test Name From 1st screen',
        phoneNumber: '97645',
    };
    this.props.onRegister(newUser);
}
```

**Comment by vivekshah-zymr** [comment]
@ItsNoHax  Yes. That's my bad. Silly mistake.
